=== dojetin/ClassroomExercises/Lenguaje de marcas/XML/cosonuevo/schema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="atomos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="atomo">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="nombre"/>
              <xs:element type="xs:string" name="simbolo"/>
              <xs:element type="xs:byte" name="numero_atomico"/>
              <xs:element type="xs:string" name="peso_atomico"/>
              <xs:element name="punto_ebullicion">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="unidades"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="carga">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:byte">
                      <xs:attribute type="xs:string" name="tipo"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="estado"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== dojetin/ClassroomExercises/Lenguaje de marcas/XML/cosonuevo/doc1.xml
<?xml version="1.0" encoding="UTF-8"?>
<atomos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/Usuario/OneDrive/Documents/Lenguaje%20de%20marcas/XML/cosonuevo/schema.xsd">
    <atomo estado="gaseoso">
      <nombre>Hidrogeno</nombre>
      <simbolo>H</simbolo>
      <numero_atomico>1</numero_atomico>
      <peso_atomico>0,0001</peso_atomico>
      <punto_ebullicion unidades="kelvin">0,1</punto_ebullicion>
      <carga tipo="negativa">1</carga>
    </atomo>
</atomos>
