=== dojetin/ClassroomExercises/Lenguaje de marcas/XML/DTD/Entrega/ej1.dtd
<!ELEMENT almacen (articulo+)>
<!ELEMENT articulo (codigo, nombre, descripcion?, categoria+, precio?, publico?)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT categoria (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT publico EMPTY>

=== dojetin/ClassroomExercises/Lenguaje de marcas/XML/DTD/Entrega/EJ1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE almacen SYSTEM "file:/C:/Users/Usuario/OneDrive/Documents/Lenguaje%20de%20marcas/XML/DTD/ej1.dtd">
<almacen>
<articulo>
<codigo>1</codigo>
<nombre>pepe</nombre>
<descripcion>Frikki</descripcion>
<categoria>persona</categoria>
<precio>14</precio>
</articulo>
<articulo>
<codigo>2</codigo>
<nombre>pizza</nombre>
<categoria>comida</categoria>
</articulo>
</almacen>
