=== dojetin/ClassroomExercises/Lenguaje de marcas/XML/DTD/Entrega/ej2.dtd
<!ELEMENT serie (capitulos+)>
<!ELEMENT capitulos (temporada, numero, titulo, sinopsis?, duracion, opiniones+)>
<!ELEMENT temporada (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT sinopsis (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT opiniones (#PCDATA)>

=== dojetin/ClassroomExercises/Lenguaje de marcas/XML/DTD/Entrega/EJ2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE serie SYSTEM "file:/C:/Users/Usuario/OneDrive/Documents/Lenguaje%20de%20marcas/XML/DTD/ej2.dtd">
<serie>
<capitulos>
<temporada>1</temporada>
<numero>4</numero>
<titulo>Pato</titulo>
<duracion>1:45</duracion>
<opiniones>Mal</opiniones>
</capitulos>
<capitulos>
<temporada>5</temporada>
<numero>2</numero>
<titulo>Pato</titulo>
<duracion>1:5</duracion>
<opiniones>Bien</opiniones>
</capitulos>
</serie>
