=== dojetin/ClassroomExercises/Lenguaje de marcas/XML/EXAM2022/pagos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="pagos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string" maxOccurs="3" default="A"/>
        <xs:element name="fechaNacimiento" type="xs:string"/>
        <xs:element name="hora" type="xs:string" maxOccurs="unbounded"/>
        <xs:element name="precio" type="xs:string"/>
        <xs:element name="cantidad" type="xs:string" fixed="678"/>
        <xs:element name="pagado" type="xs:string" default="false"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== dojetin/ClassroomExercises/Lenguaje de marcas/XML/EXAM2022/pagos.xml
<?xml version="1.0" encoding="UTF-8"?>
<pagos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/Usuario/OneDrive/Documents/Lenguaje%20de%20marcas/XML/EXAM2022/pagos.xsd">
  <nombre>Javier Toledano</nombre>
  <fechaNacimiento>1979-02-04</fechaNacimiento>
  <hora>23:55:15</hora>
  <hora>23:55:15</hora>
  <precio>123.56</precio>
  <cantidad>678</cantidad>
  <pagado>true</pagado>
</pagos>
