=== dojetin/ClassroomExercises/Lenguaje de marcas/XML/entregaXSD/ej10.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="heladeria">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="helado" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="helado">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="sabor"/>
        <xs:element ref="tipo"/>
        <xs:element ref="tamaño"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>  
  
  <xs:element name="sabor">
              <xs:simpleType>
                  <xs:restriction base="xs:string">
                              <xs:enumeration value="chocolate"></xs:enumeration>
                              <xs:enumeration value="fresa"></xs:enumeration>
                              <xs:enumeration value="vainilla"></xs:enumeration>
                              <xs:enumeration value="limon"></xs:enumeration>
                  </xs:restriction>
              </xs:simpleType>
  </xs:element>
  
    <xs:element name="tipo">
              <xs:simpleType>
                  <xs:restriction base="xs:string">
                              <xs:enumeration value="cono"></xs:enumeration>
                              <xs:enumeration value="tarrina"></xs:enumeration>
                  </xs:restriction>
              </xs:simpleType>
  </xs:element>
  
    <xs:element name="tamaño">
              <xs:simpleType>
                  <xs:restriction base="xs:string">
                              <xs:enumeration value="grande"></xs:enumeration>
                              <xs:enumeration value="mediano"></xs:enumeration>
                              <xs:enumeration value="pequeño"></xs:enumeration>
                  </xs:restriction>
              </xs:simpleType>
  </xs:element>
</xs:schema>

=== dojetin/ClassroomExercises/Lenguaje de marcas/XML/entregaXSD/ej10.xml
<?xml version="1.0" encoding="UTF-8"?>
<heladeria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/Usuario/OneDrive/Documents/Lenguaje%20de%20marcas/XML/entregaXSD/ej10.xsd">
<helado>
      <sabor>fresa</sabor>
      <tipo>cono</tipo>
      <tamaño>grande</tamaño>
</helado>

<helado>
      <sabor>chocolate</sabor>
      <tipo>cono</tipo>
      <tamaño>mediano</tamaño>
</helado>

<helado>
      <sabor>limon</sabor>
      <tipo>tarrina</tipo>
      <tamaño>pequeño</tamaño>
</helado>

<helado>
      <sabor>vainilla</sabor>
      <tipo>tarrina</tipo>
      <tamaño>grande</tamaño>
</helado>
</heladeria>
