=== dojetin/ClassroomExercises/Lenguaje de marcas/XML/entregaXSD/ej3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  
  <xs:element name="lista_de_cargos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="cargo" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
    <xs:element name="cargo">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="uniforme" maxOccurs="unbounded"/>
      </xs:sequence>
              <xs:attribute name="nombre" type="xs:string"></xs:attribute>
              <xs:attribute name="sueldo" type="xs:integer"></xs:attribute>
    </xs:complexType>
  </xs:element>
  
      <xs:element name="uniforme">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="gorro" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="prenda_sup" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="prenda_inf" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
    <xs:element name="gorro">
              <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                        <xs:attribute name="tipo" type="xs:string"></xs:attribute>
                                        <xs:attribute name="color" type="xs:string"></xs:attribute>
                            </xs:extension>
                        </xs:simpleContent>
              </xs:complexType>
    </xs:element>
    
        <xs:element name="prenda_sup">
              <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                        <xs:attribute name="tipo" type="xs:string"></xs:attribute>
                                        <xs:attribute name="color" type="xs:string"></xs:attribute>
                                        <xs:attribute name="manga" type="xs:string"></xs:attribute>
                            </xs:extension>
                        </xs:simpleContent>
              </xs:complexType>
    </xs:element>
    
            <xs:element name="prenda_inf">
              <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                        <xs:attribute name="tipo" type="xs:string"></xs:attribute>
                                        <xs:attribute name="color" type="xs:string"></xs:attribute>
                                        <xs:attribute name="cierre" type="xs:string"></xs:attribute>
                            </xs:extension>
                        </xs:simpleContent>
              </xs:complexType>
    </xs:element>
</xs:schema>

=== dojetin/ClassroomExercises/Lenguaje de marcas/XML/entregaXSD/ej3.xml
<?xml version="1.0" encoding="UTF-8"?>
<lista_de_cargos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/Usuario/OneDrive/Documents/Lenguaje%20de%20marcas/XML/entregaXSD/ej3.xsd">
      <cargo nombre="guru" sueldo="60000">
            <uniforme>
                  <gorro tipo="turbante" color="rojo"></gorro>
                  <prenda_sup tipo="chilaba" color="azul" manga="larga"></prenda_sup>
            </uniforme>
      </cargo>
      <cargo nombre="operador" sueldo="4800">
            <uniforme>
                  <gorro tipo="peineta" color="floreada"></gorro>
            </uniforme>
      </cargo>
      <cargo nombre="programador" sueldo="40000">
            <uniforme>
                  <prenda_sup tipo="camiseta" color="verde" manga="corta"></prenda_sup>
                  <prenda_inf tipo="chandal" color="caqui" cierre="cuerda"></prenda_inf>
                  <prenda_inf tipo="zapatos" color="negro" cierre="cordón"></prenda_inf>
            </uniforme>
      </cargo>
</lista_de_cargos>
