=== dojetin/ClassroomExercises/Lenguaje de marcas/XML/entregaXSD/ej4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="listin">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="persona" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  
    <xs:element name="persona">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" maxOccurs="unbounded"/>
        <xs:element name="email" maxOccurs="unbounded"/>
        <xs:element ref="relacion" minOccurs="0"/>
      </xs:sequence>
              <xs:attribute name="sexo" type="xs:string"></xs:attribute>
              <xs:attribute name="id" type="xs:string"></xs:attribute>
    </xs:complexType>
  </xs:element>
  
  
      <xs:element name="relacion">
    <xs:complexType>
              <xs:simpleContent>
                  <xs:extension base="xs:string">
                              <xs:attribute name="amigo-de" type="xs:string"></xs:attribute>
                  </xs:extension>
              </xs:simpleContent>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== dojetin/ClassroomExercises/Lenguaje de marcas/XML/entregaXSD/ej4.xml
<?xml version="1.0" encoding="UTF-8"?>

<listin xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/Usuario/OneDrive/Documents/Lenguaje%20de%20marcas/XML/entregaXSD/ej4.xsd">
      <persona sexo="hombre" id="manu">
          <nombre>Manuel Martin</nombre>
          <email>rick@yahoo.com</email>
          <relacion amigo-de="antonia"></relacion>
      </persona>
      <persona sexo="mujer" id="antonia">
          <nombre>Antonia Casta</nombre>
          <email>castal@micasa.com</email>
      </persona>
</listin>
