=== dojetin/ClassroomExercises/Lenguaje de marcas/XML/entregaXSD/ej6.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="biblioteca">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="libro" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
      <xs:element name="libro">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="titulo"/>
        <xs:element ref="autor" maxOccurs="unbounded"/>
        <xs:element ref="editorial"/>
        <xs:element name="fechapublicacion"/>
      </xs:sequence>
            <xs:attribute name="nick" type="xs:string"></xs:attribute>
    </xs:complexType>
  </xs:element>
  
        <xs:element name="autor">
    <xs:complexType>
              <xs:simpleContent>
                  <xs:extension base="xs:string">
                              <xs:attribute name="id" type="xs:string"></xs:attribute>
                              <xs:attribute name="idref" type="xs:string"></xs:attribute>
                  </xs:extension>
              </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
        <xs:element name="editorial">
    <xs:complexType>
              <xs:simpleContent>
                  <xs:extension base="xs:string">
                              <xs:attribute name="id" type="xs:string"></xs:attribute>
                              <xs:attribute name="idref" type="xs:string"></xs:attribute>
                  </xs:extension>
              </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== dojetin/ClassroomExercises/Lenguaje de marcas/XML/entregaXSD/ej6.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/Usuario/OneDrive/Documents/Lenguaje%20de%20marcas/XML/entregaXSD/ej6.xsd">
      <libro nick="sole tura">
            <titulo>Constituciones y períodos constituyentes de España</titulo>
            <autor id="tura">Solé Tura</autor>
            <editorial id="grigalbo">Grigalbo</editorial>
            <fechapublicacion>01-04-1980</fechapublicacion>
      </libro>
      <libro nick="la pepa">
            <titulo>La incleible historia de Pepe Bayo</titulo>
            <autor idref="tura"/>
            <autor id="garcía">Antonio García Fernández</autor>
            <editorial idref="grigalbo"/>
            <fechapublicacion>21-10-1990</fechapublicacion>
      </libro>
      <libro nick="condemor">
            <titulo>Aquí llega Condemor, el pecador de la pradera</titulo>
            <autor id="chiquito">Gregorio Sánchez Fernández</autor>
            <editorial>Anaya</editorial>
            <fechapublicacion>01-05-1996</fechapublicacion>
      </libro>
</biblioteca>
