=== dojetin/ClassroomExercises/Lenguaje de marcas/XML/entregaXSD/ej8.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="editoriales">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="editorial" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  
      <xs:element name="editorial">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre"/>
        <xs:element name="direccion"/>
        <xs:element name="email" minOccurs="0"/>
        <xs:element name="pagina" minOccurs="0"/>
        <xs:element name="telefono" minOccurs="0"/>
        <xs:element name="fax" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>  
  
</xs:schema>

=== dojetin/ClassroomExercises/Lenguaje de marcas/XML/entregaXSD/ej8.xml
<?xml version="1.0" encoding="UTF-8"?>
<editoriales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/Usuario/OneDrive/Documents/Lenguaje%20de%20marcas/XML/entregaXSD/ej8.xsd">
<editorial>
    <nombre>Anaya</nombre>
    <direccion>Sucasa n6</direccion>
    <email>anayaoficinas@sucasa6.com</email>
</editorial>
<editorial>
    <nombre>S.L</nombre>
    <direccion>SLcalleinvent n7</direccion>
    <pagina>anayasucasa.es</pagina>
</editorial>
<editorial>
    <nombre>ofertas</nombre>
    <direccion>ofertitis n9</direccion>
    <pagina>jairo pruebameasa.es</pagina>
    <telefono>637837389</telefono>
    <fax>73637826373763837</fax>
</editorial>
</editoriales>
