=== dojetin/ClassroomExercises/Lenguaje de marcas/XML/entregaXSD/ej9.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="tabla">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="atomo" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  
      <xs:element name="atomo">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre"/>
        <xs:element name="simbolo"/>
        <xs:element name="numeroAtomico"/>
        <xs:element name="pesoAtomico"/>
        <xs:element ref="puntoEbullicion"/>
        <xs:element ref="densidad"/>
      </xs:sequence>
                  <xs:attribute name="estado" type="xs:string"></xs:attribute>
    </xs:complexType>
  </xs:element>  
  
        <xs:element name="puntoEbullicion">
    <xs:complexType>
              <xs:simpleContent>
                  <xs:extension base="xs:string">
                              <xs:attribute name="unidades" type="xs:string"></xs:attribute>
                  </xs:extension>
              </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
          <xs:element name="densidad">
    <xs:complexType>
              <xs:simpleContent>
                  <xs:extension base="xs:string">
                              <xs:attribute name="unidades" type="xs:string"></xs:attribute>
                  </xs:extension>
              </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== dojetin/ClassroomExercises/Lenguaje de marcas/XML/entregaXSD/ej9.xml
<?xml version="1.0" encoding="UTF-8"?>
<tabla xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/Usuario/OneDrive/Documents/Lenguaje%20de%20marcas/XML/entregaXSD/ej9.xsd">
    <atomo estado="gaseoso">
      <nombre>Oxigeno</nombre>
      <simbolo>O</simbolo>
      <numeroAtomico> 14</numeroAtomico>
      <pesoAtomico>15,99u</pesoAtomico>
      <puntoEbullicion unidades="ºC">-183</puntoEbullicion>
      <densidad unidades="g/l">1,429</densidad>
    </atomo>
    
      <atomo estado="solido">
      <nombre>Carbono</nombre>
      <simbolo>C</simbolo>
      <numeroAtomico> 6</numeroAtomico>
      <pesoAtomico>12,01u</pesoAtomico>
      <puntoEbullicion unidades="ºC">4.800</puntoEbullicion>
      <densidad unidades="g/cm3">2,25</densidad>
    </atomo>
    
      <atomo estado="liquido">
      <nombre>Cloro</nombre>
      <simbolo>Cl</simbolo>
      <numeroAtomico> 17</numeroAtomico>
      <pesoAtomico>35,143u</pesoAtomico>
      <puntoEbullicion unidades="ºC">-34</puntoEbullicion>
      <densidad unidades="g/ml">0,573</densidad>
    </atomo>

</tabla>
